### ISSUE TITLE
switching station delayed switch-off

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/technic#11]
## Tasks

* [x] run switching stations in a globalstep
* [x] switching-station "pool" with last-visited time
* [x] switching station abm refreshes last-visited time
* [x] configurable delay
* [x] metrics

## Use-case

* non-afk mining and production
* better reliable machines
